from __future__ import absolute_import
from __future__ import division
from __future__ import print_function


import os
import sys

CONST_ARES_PATH = os.getcwd()

CONST_ARES = True

CONST_ARES_SEPARATOR  = "/"

CONST_SUB_DIRECTORY = '..'  

CONST_ARES_CLASSES = 'classes'

CONST_ARES_CORE = 'core'

CONST_ARES_LOG = 'log'

CONST_ARES_LANG = 'lang'

CONST_FILE_LOG = 'errorLogs.aee'#Ares Entretetainement Error Extension

CONST_FILE_BACKUP_ERRORS = 'errorsBackUp.aee'
"""CONST_SUB_DIRECTORY + CONST_ARES_SEPARATOR +"""
CONST_PATH_SUB_ERRORLOG =  CONST_ARES_LOG + CONST_ARES_SEPARATOR + CONST_FILE_LOG
""" CONST_SUB_DIRECTORY + CONST_ARES_SEPARATOR + """
CONST_PATH_SUB_BACKUP_ERRORS =CONST_ARES_LOG + CONST_ARES_SEPARATOR + CONST_FILE_BACKUP_ERRORS


CONST_INSTALLED = True

PARAM_DEV_MODE = True

PARAM_LANG_DEFAULT = 'FR'

PARAM_SALT = 'ISLOVIVA159753'

PARAM_CUSTOM_HASH_SALT = True

PARAM_CONSOLE_MODE = True


PATH_LANG = CONST_ARES_PATH+CONST_ARES_SEPARATOR+CONST_ARES_LANG+CONST_ARES_SEPARATOR


sys.path.append(CONST_ARES_PATH)
sys.path.append(CONST_ARES_PATH+CONST_ARES_SEPARATOR+CONST_ARES_CLASSES)
sys.path.append(CONST_ARES_PATH+CONST_ARES_SEPARATOR+CONST_ARES_CORE)
sys.path.append(CONST_ARES_PATH+CONST_ARES_SEPARATOR+CONST_ARES_LOG)
sys.path.append(CONST_ARES_PATH+CONST_ARES_SEPARATOR+CONST_ARES_LANG)
