#INSTALLED EXERCICES

#CONSTANT
CONST_ARES_SEPARATOR  = "/"

CONST_ARES_CLASSES = 'classes'

CONST_ARES_CORE = 'core'

CONST_ARES_LOG = 'log'

CONST_ARES_LANG = 'lang'

PARAM_CONSOLE_MODE= True

ARES_SETTINGS_DATABASE_NAME = 'database.db'
ARES_SETTINGS_DATABASE_PATH = 'database/'
PARAM_SALT = 'ISLOVIVA159753'
PARAM_CUSTOM_HASH_SALT = True



CONST_FILE_LOG = 'errorLogs.aee'#Ares Entretetainement Error Extension

CONST_FILE_BACKUP_ERRORS = 'errorsBackUp.aee'
"""CONST_SUB_DIRECTORY + CONST_ARES_SEPARATOR +"""
CONST_PATH_SUB_ERRORLOG =  CONST_ARES_LOG + CONST_ARES_SEPARATOR + CONST_FILE_LOG
""" CONST_SUB_DIRECTORY + CONST_ARES_SEPARATOR + """
CONST_PATH_SUB_BACKUP_ERRORS =CONST_ARES_LOG + CONST_ARES_SEPARATOR + CONST_FILE_BACKUP_ERRORS



CONST_FILE_ROBOT = "Robot.aee"
CONST_PATH = "settings/"
CONST_FILE_ROBOT = CONST_PATH + CONST_FILE_ROBOT

CONST_PRINT = True
CONST_TIME_SLEEP_CARDIO_MESURE = 10
CONST_COEFF_CARDIO_MESURE = 60 / CONST_TIME_SLEEP_CARDIO_MESURE

CONST_EXTENSION = '.aee'
CONST_PATH_TRAINING = 'modules/Training/'
CONST_TRAINING = "modules.Training"


TypeExercices = ['ExerciceCardioVascular','ExerciceMuscular']

