dErrorDictionary = {	
					'Test' : 'It\'s a test message' 

                              ,'ErrorClassModuleExistence' : 'Class don\'t exist, please try another class or reinstall modules'


                              ,'ErrorInstallLang' : 'Bad Installation of Ares, retry installation or contact us at ares.entretainement@gmail.com '
				
                              ,'ErrorLangPhraseExistenceDictionnary' : 'La phrase n\'existe pas dans ce module'
                         }

aStandardErrorList = [
	   'SystemExit'
	  ,'KeyboardInterrupt'
	  ,'GeneratorExit'
	  ,'Exception'
      ,'StopIteration'
      ,'StandardError'
      ,'BufferError'
      ,'ArithmeticError'
      ,'FloatingPointError'
      ,'OverflowError'
      ,'ZeroDivisionError'
      ,'AssertionError'
      ,'AttributeError'
      ,'EnvironmentError'
      ,'IOError'
      ,'OSError'
      ,'EOFError'
      ,'ImportError'
      ,'LookupError'
      ,'IndexError'
      ,'KeyError'
      ,'MemoryError'
      ,'NameError'
      ,'UnboundLocalError'
      ,'ReferenceError'
      ,'RuntimeError'
      ,'NotImplementedError'
      ,'SyntaxError'
      ,'IndentationError'
      ,'TabError'
      ,'SystemError'
      ,'TypeError'
      ,'ValueError'
      ,'UnicodeError'
      ,'UnicodeDecodeError'
      ,'UnicodeEncodeError'
      ,'UnicodeTranslateError'
      ,'DeprecationWarning'
      ,'PendingDeprecationWarning'
      ,'RuntimeWarning'
      ,'SyntaxWarning'
      ,'UserWarning'
      ,'FutureWarning'
	  ,'ImportWarning'
	  ,'UnicodeWarning'
	  ,'BytesWarning']
